export const GET_TOTAL_CASHIER = "GET_TOTAL_CASHIER";
export const REFRESH_TOTAL_VALUE_CASHIER = "REFRESH_TOTAL_VALUE_CASHIER";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
